### ISSUE TITLE
Making room in battery 'at Sunrise'

### ISSUE THREAD

**Issue by cyberkryten** [CJDumbleton/ha_predbat_automations#2]
I was trying to figure out how to work things around a combination of Sunrise and IOG cheap period ending at 05:30

Throughout pv_clipping_make_room_in_battery_at_sunrise.yaml there are mentions of things being done in relation to Sunrise, so I figured I could just add an 'IF' to the sunrise time.  However, it doesn't actually use Sunrise anywhere.

All the actions are relative to when input_number.pv_clipped_in_next_24_hours is updated - I assume in your system you only update the calculations once, at sunrise, so it is true for you.

However, it means if you rerun the calculation for the next 24 hours after a Solcast forecast update (mine are set at Sunrise, Noon and the halfway point of those to and then halfway between Noon and Sunset), the calcs will be redone 'now' but the actions assume now is sunrise and so it generates exports late in the day.

**Comment by CJDumbleton** [comment]
I've changed the trigger for `pv_clipping_make_room_in_battery_at_sunrise.yaml` to 2 minutes after sunrise (instead of being triggered by a change in `input_number.pv_clipped_in_next_24_hours`). Does that resolve the issue?

**Comment by cyberkryten** [comment]
Yep, that does, though I actually changed the pv_clipped automation to only run once, just after sunrise instead!

I'll see how it all goes tomorrow and report back

**Comment by cyberkryten** [comment]
So, it ran successfully but it backfills export slots towards sunrise, which is exactly what the docs say it does.

That's just not going to work for me as the slots were planned to start at 08:30 and end at 11:30 as I'll be hitting the clipping by 09:30

I think I'll have to rework things to start much earlier.  For now, filling from sunrise onwards will probably be OK but when that gets to the IOG end time of 05:30 there's other complications, like has Predbat finished charging the battery enough.  So I suspect I'll probably end up triggering it at 05:30 and hope.

I guess it shows why Trefor has found it so hard to come up with a clipping model in Predbat that works for everyone!

**Comment by cyberkryten** [comment]
OK, I've been playing with some options and this is what I've come up with to iterate through possible slots and export.

However, I can't find a way to actually trigger the Exports!

I'm assuming that's why your original script has an entry for each slot in isolation, because there's no way to call SELECT multiple times from a single loop?

```
        {# Define the Export Limit for the system - either Inverter Capacity or any Export Limit imposed by DNO #}
        {%- set SystemExportLimit = 3.6 -%}
        {# The Half Hourly slots we want to use - probably a better way to do this but this is simple #}
        {%- set ExportTimes = ['05:30:00', '06:00:00', '06:30:00', '07:00:00', '07:30:00', '08:00:00', '08:30:00', '09:00:00', '09:30:00', '10:00:00', '10:30:00'] -%}

        {# Calculate the Half Hourly Export we expect (max, it will be lower once there is solar excess #}        
        {%- set SlotExportKWH = SystemExportLimit / 2 -%}
        {# Amount of excess solar we need to get rid of to avoid clipping #}
        {%- set PVClipped = namespace(value=float(states('input_number.pv_clipped_in_next_24_hours'),0)) -%}   

        {%- set tNow = now().strftime("%s") | int -%}
        {%- set tNow = today_at("00:05:00") .strftime("%s") | int -%}
        
        {# Loop through our possible export slots #}        
        {%- for ExportSlot in ExportTimes -%}
          {# Do we still need to export more energy #}        
          {%- if PVClipped.value > 0 -%}
            {%- set tSlot = today_at(ExportSlot).strftime("%s") | int -%}
            {# Only use future slots - if time is in the past, then don't schedule export #}        
            {%- if tSlot > tNow -%}
              {# Setup this slot to Export #}
              {{-"Force Export during "-}}{{-as_datetime(tSlot)-}}{{-"\n\t"-}}
              {# Deduct this export from the total #}        
              {%- set PVClipped.value = PVClipped.value - SlotExportKWH -%}
            {%- endif -%}
          {%- endif -%}
        {%- endfor -%}
        {# We didn't find enough slots to Anything left here was #}                
        Export Remaining {{ (PVClipped.value if (PVClipped.value ) > 0 else 0) | round(1) }} kWh
```

**Comment by CJDumbleton** [comment]
I've brought all export slots forward one hour in `pv_clipping_make_room_in_battery_at_sunrise.yaml` I think that will still work okay for me. I can't remember why I set it so far out to begin with - maybe it is different at different times of year.

I'm not aware of a way to call SELECT within a yaml loop. You might be able to create a loop within the automation. If you edit the automation in Home Assistant using the visual editor rather than yaml, you will see 'ADD BUILDING BLOCK' at the bottom of the 'Then do' section. You can then add a repeat element. In your Repeat element, you could update input_number.pv_clipped_in_next_24_hours each time - subtracting the SlotExportKWH each time. You could perhaps delay for a second or so to make sure the next repeat reads the updated value.

I don't think this approach will work for me, because when I'm exporting, a lot of my inverter/DNO capacity is taken up with solar export. I can't really judge how much the battery will actually be exporting at that time. Therefore, I can't really judge how much extra room I will make in the battery in a single 30-minute export slot. For example, today at 09:30, I was already exporting over 3.5kW of solar energy. So, I would only have been able to export 1.5kW from the battery before I hit my 5kW inverter/DNO limit. Even though my battery's maximum discharge rate is 3.6 kW. As the net solar export is also affected by load, it is very difficult to judge.

**Comment by CJDumbleton** [comment]
I've changed my mind. I'm going to give your loop approach a go. I used a [repeat element](https://github.com/CJDumbleton/ha_predbat_automations/blob/main/pv_clipping_make_room_in_battery_at_sunrise.yaml).  I'll see how I go tomorrow!

**Comment by cyberkryten** [comment]
Did the loop work?  I've actually gone for something simpler in the end - just checking every half hour if there's still clipping expected and if so export again down to 50% SoC

I changed the forecast to stop at midnight so it only has the 'today' figure and set the 'step' on the helper to 1.8 which is how much I can export in a 30min slot.

```
alias: PV clipping - Forced Export Today
description: ""
triggers:
  - trigger: time_pattern
    minutes: /30
conditions:
  - condition: numeric_state
    entity_id: sensor.calc_battery_all_state
    above: 50
actions:
  - if:
      - condition: time
        after: "05:30:00"
      - condition: sun
        before: sunset
      - condition: numeric_state
        entity_id: input_number.pv_clipped_remaining_today
        above: 0
    then:
      - action: select.select_option
        metadata: {}
        data:
          option: >
            {% set t = utcnow().strftime("%s") | int %}    {{ (t - (t%1800)) |
            timestamp_custom("%H:%M:%S") }}
        target:
          entity_id: select.predbat_manual_export
      - action: input_number.decrement
        metadata: {}
        data: {}
        target:
          entity_id: input_number.pv_clipped_remaining_today
mode: single
```

That worked this morning, but I now realise (probably) why you aimed the export later.  If you do it first thing and clear enough space in the battery, then you end up in Max Self Consumption mode and the early day solar fills the battery back up again!

I think what I need to do is just use battery state when deciding if to force export in this half hour and rerun the prediction through the day to recalculate it.   Basically if clipping > space in battery, then force export.
